- repo: local
  hooks:
    - id: custom-script
      name: custom-script
      entry: ./custom_precommit.sh
      language: script
      files: '.*\.[ch]'
    - id: custom-script-failing
      name: custom-script-failing
      entry: ./custom_precommit_failing.sh
      language: script