repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-yaml
  -   id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v13.0.0'
  hooks:
  -   id: clang-format
- repo: local
  hooks:
  - id: custom-script
    name: custom-script
    entry: ./custom_precommit.sh
    language: system
    files: '.*\.[ch]'
  - id: custom-script-failing
    name: custom-script-failing
    entry: ./custom_precommit_failing.sh
    language: system
